name: Docker Build CI

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Docker
        run: docker build --tag travel-api:$(date +%s) ./backend